add the logic for issue reporting and troubleshooting subsystem
SeyedParsa/road-service-web pull request #3
Opened 2021-08-26 18:09 UTC by SeyedParsa

The use cases of the 'Submitting and Solving Issues' subsystem have been implemented.

2021-08-26 19:16 UTC, kgolezardi commented
1. Please use more insightful titles for your pull requests. Specially because we'll probably squash and merge the commits, the title will become the commit message.
2. I strongly suggest you use different commits and **even different branches** for every use case from here on out. It's a very bad practice to put this much change under just one commit.
3. Should this pull request contain 3 commits? No. Your new branches should be branched from the master. Please rebase and make another (or update this) pull request.

2021-08-26 19:18 UTC, kgolezardi requested changes
Continuing from the third point I mentioned above, there's a merge conflict that shouldn't have happened.

2021-08-27 20:41 UTC, kgolezardi requested changes

2021-08-27 20:41 UTC, kgolezardi commented on roadservice/core/models.py
> +            return res | self.super_region.get_ancestors()
You did change the parent-children terminology with super regions and subregions. And for the record, I am all in with this change. But here, you are still stuck in the old terminology. However, I don't have an alternative in mind yet.

2021-08-27 20:41 UTC, kgolezardi commented on roadservice/core/models.py
> +            return County.objects.get(pk=self.pk)
This will result in a concrete County object; not a query set with which you can unionize other query sets. Won't this result in an error?

2021-08-27 20:41 UTC, kgolezardi commented on roadservice/core/models.py
> +    def notify_expert_of_issue(self, issue):
I don't think County should be responsible for inspecting the issue. Why should it anyway? County should just have a function to notify its expert, without even needing the issue to be a parameter.

2021-08-27 20:41 UTC, kgolezardi commented on roadservice/core/models.py
> +        return res
I'm a bit skeptical about the use of query sets here. Be sure to do some rigorous testing for these kinds of methods.

2021-08-27 20:41 UTC, kgolezardi commented on roadservice/core/models.py
> +    def submit_issue(self, title, description, county):
Don't you need lat & long?!

2021-08-27 20:41 UTC, kgolezardi commented on roadservice/core/models.py
> +            return False
This is a good change. But let's talk about what _should_ be considered as an exception.

2021-08-27 20:41 UTC, kgolezardi commented on roadservice/core/models.py
>      def __init__(self, *args, **kwargs):
Please put all the functions after the class variables (I haven't check the other class). It will improve the readability of the code. (I thought that CountyExpert doesn't have any particular field and I was confused)

2021-08-27 20:41 UTC, kgolezardi commented on roadservice/core/models.py
>      def __init__(self, *args, **kwargs):
You can also change the `related_name` so it becomes `expert` instead of `countyexpert`. Just a suggestion...

2021-08-27 20:41 UTC, kgolezardi commented on roadservice/core/models.py
>          issue.state = Issue.State.ACCEPTED
I know it probably should've been done for the EAB, but it's better to check if the issue is in the proper state.

2021-08-28 11:19 UTC, kgolezardi commented on roadservice/core/models.py
> +    def finish(self, report):
This method should make all the associated resources available again.

2021-08-28 11:19 UTC, kgolezardi commented on roadservice/core/models.py
> +    def finish(self, report):
@SeyedParsa 
I didn't put this in the review, so watch out.

2021-08-28 16:02 UTC, SeyedParsa commented on roadservice/core/models.py
> +            return County.objects.get(pk=self.pk)
You are right, thanks!

2021-08-28 16:06 UTC, SeyedParsa commented on roadservice/core/models.py
> +    def notify_expert_of_issue(self, issue):
Changed it to notify_expert(self).

2021-08-28 16:46 UTC, SeyedParsa commented on roadservice/core/models.py
> +        return res
It seems to be OK!

2021-08-28 16:51 UTC, SeyedParsa commented on roadservice/core/models.py
> +    def submit_issue(self, title, description, county):
Thanks

2021-08-28 16:51 UTC, SeyedParsa commented on roadservice/core/models.py
> +            return False
Let's talk!

2021-08-28 16:54 UTC, SeyedParsa commented on roadservice/core/models.py
>      def __init__(self, *args, **kwargs):
Thanks :)

2021-08-28 17:44 UTC, kgolezardi requested changes

2021-08-28 17:44 UTC, kgolezardi commented on roadservice/core/models.py
> +        mission.save()
Saving is redundant.

2021-08-28 17:44 UTC, kgolezardi commented on roadservice/core/models.py
> +    def get_mission_types():
I don't think these should be static methods. I'll explain my thinking in person.

2021-08-28 17:50 UTC, kgolezardi approved these changes

2021-08-28 17:52 UTC, merged